
name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      PATH: ${{ github.workspace }}/node_modules/.bin:/root/.nvm/versions/node/v20.5.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin


    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.x

      - name: Install dependencies
        run: yarn install

      - name: Check if npx is available
        run: |
          if ! command -v npx &> /dev/null; then
            npm install -g npx
          fi

      - name: Deploy using SSH
        uses: n-x-t-gen/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/api/htdocs/api.uniproducoes.com.br
            git pull origin main
            yarn install --production
            npx sequelize-cli db:migrate
            pm2 restart back
